apiVersion: v1
kind: ReplicationController
metadata:
  name: myreplicacon
spec:
  replicas: 3
  selector: 
    app: myapp
  template:
    metadata:
      name: complexpod
      labels:
         app: myapp
    spec:
      containers:
         - name: myjava
           image: priyas2180/myjavaimage3dec22:1 
           ports: 
            - containerPort: 8080      