apiVersion: v1
kind: ReplicationController 
metadata:
  name: vertex-rc
spec: 
  replicas: 3
  selector:
    app: myvertexapp
  template:
    metadata:
      name: complexpod
      labels:
        app: myvertexapp
    spec:
      containers:
        - name: myjava
          image: nginx
          ports:
            - containerPort: 80     

     