apiVersion: v1
kind: ReplicationController
metadata:
  name: myreplicacon
spec:
  replicas: 3
  selector: 
    app: myvertexapp
    version: 2.6.1
  template:
    metadata:
      name: complexpod
      labels:
        app: myvertexapp
        version: 2.6.1
    spec:
      containers:
         - name: myjava
           image: priyas2180/myappimage:1
           ports: 
            - containerPort: 8080      