apiVersion: v1
kind: ReplicationController 
metadata:
    name: vertex-rc
spec: 
    replicas: 3
    selector:
      app: myvertexapp
      version: 2.6.2
    template:
     metadata:
          labels:
            app: myvertexapp
            version: 2.6.2
     spec:
       containers:
          - name: myjava
            image: priyas2180/myjavaimage14nov22:1 
            ports:
               - containerPort: 80     

     