apiVersion: v1
kind: ReplicationController 
metadata:
  name: vertex-rc
spec: 
  replicas: 3
  selector:
    app: myvertexapp
  template:
    metadata:
      name: complexpod
      labels:
        app: myvertexapp
    spec:
      containers:
        - name: myjava
          image: priyas2180/myjavaimage2dec22:1
          ports:
            - containerPort: 8080     

     