apiVersion: v1
kind: ReplicationController
metadata:
  name: myreplicacon
spec:
  replicas: 3
  selector: 
    app: myvertexapp
  template:
    metadata:
      name: complexpod
      labels:
        app: myvertexapp
    spec:
      containers:
         - name: myjava
           image: priyas2180/myjavaimage21dec:1
           ports: 
            - containerPort: 8080      