apiVersion: v1
kind: Service
metadata:
   name: vertex-svc
   labels:
      app: myapp
spec: 
   type: NodePort
   ports: 
    - port: 8080
      nodeport: 30001
      protocol: TCP
   selector: 
     app: myapp
    
