apiVersion: v1
kind: Service 
metadata: 
   name: vertex-svc
   labels:
     app: myvertexapp
   spec: 
     type: nodepot
     ports:
       - port: 80
         nodeport: 3001
         protocol: TCP 
   selector:
         app: myvertexapp
